export class Constants {
    static readonly OVERVIEW_URL = "/overview/"
    static readonly PRODUCTS_URL = "/products/"
    static readonly CATEGORIES_URL = "/product-categories/"
    static readonly ADD_PRODUCT_URL = "/products/add/"
    static readonly EDIT_PRODUCT_URL = "/products/edit/"
    static readonly ADD_CATEGORY_URL = "/product-categories/add/"
    static readonly STORE_PROFILE_URL = "/store-profile/"
    static readonly LOGIN_URL = "/"

    static readonly LOGIN_API_URL = "/api/auth/login"
    static readonly LOGOUT_API_URL = "/api/auth/logout"
    static readonly GET_PRODUCTS_API = "/api/products/get"
    static readonly GET_CATEGORY_API = "/api/category/get"
    static readonly CREATE_PRODUCT_API = "/api/products/create"
    static readonly UPDATE_PRODUCT_API = "/api/products/update"
    static readonly DELETE_PRODUCT_API = "/api/products/delete/"
    static readonly GET_PRODUCT_DETAIL_API = "/api/products/get/"
    static readonly DELETE_CATEGORY_API = "/api/category/[sku]/delete/"
}